--- #YAML:1.0
name:               FormValidator-Simple-Plugin-CustomConstraint
version:            0.01
abstract:           Custom constraint support for FormValidator::Simple
author:
    - Alex Pavlovic <alex.pavlovic@taskforce-1.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    FormValidator::Simple:  0.29
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
